Jatkuvan MVC/Models/ErrorViewModel.cs
using System;

namespace Jatkuvan_MVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Jatkuvan MVC/Models/JatkuvaTehtavaContext.cs
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Jatkuvan_MVC.Models
{
    public partial class JatkuvaTehtavaContext : DbContext
    {
        public JatkuvaTehtavaContext()
        {
        }

        public JatkuvaTehtavaContext(DbContextOptions<JatkuvaTehtavaContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Topic> Topic { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. See http://go.microsoft.com/fwlink/?LinkId=723263 for guidance on storing connection strings.
                optionsBuilder.UseSqlServer("server=DESKTOP-F5NJUA7\\MSSQLSERVER01;database=JatkuvaTehtava;trusted_connection=true");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Topic>(entity =>
            {
                entity.Property(e => e.CompletionDate).HasColumnType("datetime");

                entity.Property(e => e.Description)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.Source)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.StartLearningDate).HasColumnType("datetime");

                entity.Property(e => e.Title)
                    .IsRequired()
                    .HasMaxLength(255)
                    .IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}

Jatkuvan MVC/Models/Topic.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Jatkuvan_MVC.Models
{
    public partial class Topic
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int? TimeToMaster { get; set; }
        public int? TimeSpent { get; set; }
        public string Source { get; set; }
        [DataType(DataType.Date)]
        public DateTime? StartLearningDate { get; set; }
        public bool? InProgress { get; set; }
        [DataType(DataType.Date)]
        public DateTime? CompletionDate { get; set; }
    }
}

Jatkuvan MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Jatkuvan_MVC.Models;

namespace Jatkuvan_MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Jatkuvan MVC/Controllers/LueController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Jatkuvan_MVC.Models;

namespace Jatkuvan_MVC.Controllers
{
    public class LueController : Controller
    {
        private readonly JatkuvaTehtavaContext _context = new JatkuvaTehtavaContext();

        public LueController()
        {
            
        }

        // GET: Lue
        public async Task<IActionResult> Index()
        {
            return View(await _context.Topic.ToListAsync());
        }

        // GET: Lue/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var topic = await _context.Topic
                .FirstOrDefaultAsync(m => m.Id == id);
            if (topic == null)
            {
                return NotFound();
            }

            return View(topic);
        }

        // GET: Lue/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Lue/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,TimeToMaster,TimeSpent,Source,StartLearningDate,InProgress,CompletionDate")] Topic topic)
        {
            if (ModelState.IsValid)
            {
                _context.Add(topic);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(topic);
        }

        // GET: Lue/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var topic = await _context.Topic.FindAsync(id);
            if (topic == null)
            {
                return NotFound();
            }
            return View(topic);
        }

        // POST: Lue/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,TimeToMaster,TimeSpent,Source,StartLearningDate,InProgress,CompletionDate")] Topic topic)
        {
            if (id != topic.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(topic);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TopicExists(topic.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(topic);
        }

        // GET: Lue/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var topic = await _context.Topic
                .FirstOrDefaultAsync(m => m.Id == id);
            if (topic == null)
            {
                return NotFound();
            }

            return View(topic);
        }

        // POST: Lue/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var topic = await _context.Topic.FindAsync(id);
            _context.Topic.Remove(topic);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TopicExists(int id)
        {
            return _context.Topic.Any(e => e.Id == id);
        }
    }
}

Jatkuvan MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Well hello my friend!</h1>
    <p>Welcome to continuous exercise MVC page!</p>
</div>

Jatkuvan MVC/Views/Lue/Create.cshtml
@model Jatkuvan_MVC.Models.Topic

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Topic</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TimeToMaster" class="control-label"></label>
                <input asp-for="TimeToMaster" class="form-control" />
                <span asp-validation-for="TimeToMaster" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TimeSpent" class="control-label"></label>
                <input asp-for="TimeSpent" class="form-control" />
                <span asp-validation-for="TimeSpent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Source" class="control-label"></label>
                <input asp-for="Source" class="form-control" />
                <span asp-validation-for="Source" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartLearningDate" class="control-label"></label>
                <input asp-for="StartLearningDate" class="form-control" />
                <span asp-validation-for="StartLearningDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InProgress" class="control-label"></label>
                <input asp-for="InProgress" class="form-control" />
                <span asp-validation-for="InProgress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CompletionDate" class="control-label"></label>
                <input asp-for="CompletionDate" class="form-control" />
                <span asp-validation-for="CompletionDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Jatkuvan MVC/Views/Lue/Delete.cshtml
@model Jatkuvan_MVC.Models.Topic

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Topic</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TimeToMaster)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TimeToMaster)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TimeSpent)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TimeSpent)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Source)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Source)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartLearningDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartLearningDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InProgress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InProgress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CompletionDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CompletionDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Jatkuvan MVC/Views/Lue/Details.cshtml
@model Jatkuvan_MVC.Models.Topic

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Topic</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TimeToMaster)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TimeToMaster)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TimeSpent)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TimeSpent)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Source)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Source)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartLearningDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartLearningDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InProgress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InProgress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CompletionDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CompletionDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Jatkuvan MVC/Views/Lue/Edit.cshtml
@model Jatkuvan_MVC.Models.Topic

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Topic</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TimeToMaster" class="control-label"></label>
                <input asp-for="TimeToMaster" class="form-control" />
                <span asp-validation-for="TimeToMaster" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TimeSpent" class="control-label"></label>
                <input asp-for="TimeSpent" class="form-control" />
                <span asp-validation-for="TimeSpent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Source" class="control-label"></label>
                <input asp-for="Source" class="form-control" />
                <span asp-validation-for="Source" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartLearningDate" class="control-label"></label>
                <input asp-for="StartLearningDate" class="form-control" />
                <span asp-validation-for="StartLearningDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InProgress" class="control-label"></label>
                <input asp-for="InProgress" class="form-control" />
                <span asp-validation-for="InProgress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CompletionDate" class="control-label"></label>
                <input asp-for="CompletionDate" class="form-control" />
                <span asp-validation-for="CompletionDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Jatkuvan MVC/Views/Lue/Index.cshtml
@model IEnumerable<Jatkuvan_MVC.Models.Topic>

@{
    ViewData["Title"] = "Index";
}

<h1>Read Topics</h1>

<p>
    <a asp-action="Create">Create New Topics Darling</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TimeToMaster)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TimeSpent)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Source)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartLearningDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.InProgress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CompletionDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TimeToMaster)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TimeSpent)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Source)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartLearningDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.InProgress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CompletionDate)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Jatkuvan MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Jatkuvan_MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Jatkuvan_MVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Lue" asp-action="">Read Topics</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Jatkuvan_MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>